title: <p align="center"> John Carlo Maula </p>

logo: "/images/profile.png?raw=true" 

description:
  <p align="center"> <strong>Aspiring Data Scientist</strong> </p>
  
  <p align="center">
  <a href="pdf/JohnCarloMaula_Resume_2021.pdf">Resume</a> |
  <a href="www.linkedin.com/in/john-carlo-maula">LinkedIn</a> |
  <a href="https://github.com/johncarlomaula">GitHub</a>
  </p>
  
  <p align="justify">
  I graduated from The Ohio State University with a Bachelors in Data Analytics with a specialization in Biomedical Informatics. I also minored in Mathematics and Epidemiology.
  <br><br>
  My hobbies include listening to music, baking desserts, and reading about pop culture.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
